# Generated by Django 5.2.1 on 2025-05-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('offer', 'Offer Received')], default='pending', max_length=20)),
                ('applied_date', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
