# Generated by Django 5.2.1 on 2025-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='user_job_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user', 'user_job_id')},
        ),
    ]
