# Generated by Django 5.2.1 on 2025-05-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_user_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user_job_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
